services:
  # postgres:
  #     image: postgres:latest
  #     env_file:
  #         - .env
  #     ports:
  #         - '5432:5432'
  #     volumes:
  #         - ./data:/var/lib/postgresql/data
  #         - /etc/localtime:/etc/localtime:ro
  #         - /etc/timezone:/etc/timezone:ro

  atendimentos:
    image: atendimentos-microservice
    build:
      dockerfile: Dockerfile
      context: .
      target: atendimentos
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev
    # depends_on:
    #     - postgres
    env_file:
      - .env
    ports:
      - '3001:3001'
